blank_issues_enabled: false
contact_links:
  - name: Community Support & Questions (GitHub)
    url: https://github.com/RedVortexDev/Wplace-BlueMarble-Clean/discussions
    about: Go to the "Discussion" tab if you have questions or want to discuss Blue Marble with the community.